config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :medical_histories
  resources :appointments
  resources :patients

  match "static/data", :to => "static#data", :as => "data", :via => "get"
  match "static/db_action", :to => "static#db_action", :as => "db_action", :via => "post"
  #get "static/data", to: "appointments#data", as: :data
  #get "static/db_action", to: "appointments#db_action", as: :db_action
  match 'diary' , :to => 'static#diary',:via => "get", :as => 'diary_show'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'static#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient, optional: true
  belongs_to :user, optional: true
  validates_presence_of :start_date,:end_date

end

app/models/history.rb
class History < ApplicationRecord
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :patient,optional: true

end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user,optional: true
  validates_presence_of :first_name,:maternal_surname,:telephone,:email
  has_many :appointments, dependent: :delete_all
  validates :telephone, length: { is: 10 }
  validates :telephone, numericality: { only_integer: true }


  def self.search(search)
    where("first_name ILIKE ? OR id::varchar ILIKE ? OR last_name ILIKE ? or maternal_surname ILIKE ? ",
      "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end



  def full_name
    return first_name + " " + last_name + " " +maternal_surname
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :patients
  has_many :appointments

  validates_presence_of :first_name, :last_name, :maternal_surname, :telephone,:city,:street,:number,:country,:suburb,:cp
  validates :telephone, length: { is: 10 }
  validates :telephone, numericality: { only_integer: true }
  validates :number, numericality: { only_integer: true }
  validates :cp, numericality: { only_integer: true }
  validates :cp, length: { is: 5 }

  def full_name
  		return  tittle+" "+first_name + " "+ last_name + " " +maternal_surname
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show,:edit,:update,:destroy]
  protect_from_forgery with: :null_session

  def index
    @appointments= current_user.appointments.order("start_date ").page(params[:page]).per(10)
  end

  def new
    @appointment = Appointment.new
  end

  def create
      @appointment= Appointment.new(appointment_params)
      @appointment.user_id=current_user.id
      if @appointment.save
        redirect_to @appointment, notice: "La cita fue añadida satisfactoriamente!"
      else
        render :new
      end
  end


  def destroy
    @appointment.destroy
    redirect_to appointments_path, notice: "La cita fue eliminada satisfactoriamente"
  end


  def show
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment,notice: 'La cita fue modificado satisfactoriamente'
    else
      render :edit
    end
  end

 private

   def appointment_params
     params.require(:appointment).permit(:start_date,:end_date,:observation,:patient_id)
   end

   def set_appointment
     @appointment=Appointment.find(params[:id])
     if current_user.patients.ids.include?(@appointment.patient_id)
     else
       redirect_to patients_path, notice: "No tiene permiso para realizar esta acción"
     end

   end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
end

app/controllers/medical_histories_controller.rb
class MedicalHistoriesController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:edit,:update,:show,:destroy]

  def index
    if params[:search]
        @patients = current_user.patients.search(params[:search]).order("id ").page(params[:page]).per(10)
    else
        @patients = current_user.patients.order("id ").page(params[:page]).per(10)
    end
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient= Patient.new(patient_params)
    @patient.user_id = current_user.id

    if @patient.save
      redirect_to @patient, notice: "El paciente fue añadido satisfactoriamente!"
    else
      render :new
    end
  end

  def show
    if @patient.date_birth
      @patient.age=((Date.today - @patient.date_birth)/365).floor
    end
  end
  def edit
    if @patient.date_birth
      @patient.age=((Date.today - @patient.date_birth)/365).floor
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path, notice: 'El paciente fue eliminado satisfactoriamente!'
  end


  def update
    if @patient.update(patient_params)
      redirect_to @patient,notice: 'El paciente fue modificado satisfactoriamente'
    else
      render :edit
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name,:last_name,:maternal_surname,:age,:date_birth, :gender,:civil_status,:scholarship,:occupation,:street,:suburb,:city,:mun,:county,:telephone, :email,
    :reason_desc,:number)
  end

  def set_patient
      @patient=Patient.find(params[:id])
    if @patient.user_id == current_user.id
    else
      redirect_to patients_path, notice: "No tiene permiso para realizar esta acción"
    end

  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name,:last_name,:email,:maternal_surname,:telephone,:password, :password_confirmation,:street,:number,:city,:mun,:country,:cp,:suburb,:tittle)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @today_appointments=current_user.appointments.where(start_date:Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).order("start_date")
  end

  def diary
  end


  def data
   appointments = current_user.appointments
   render :json => appointments.map {|apmt| {
              :id => apmt.id,
              :start_date => apmt.start_date.to_formatted_s(:db),
              :end_date => apmt.end_date.to_formatted_s(:db),
              :text => "Cita de " +apmt.patient.full_name
          }
        }
 end

 def db_action
   mode = params["!nativeeditor_status"]
   id = params["id"]
   start_date = params["start_date"]
   end_date = params["end_date"]
   text = params["observation"]

   case mode
     when "inserted"
       apmt = Appointment.create :start_date => start_date, :end_date => end_date, :text => observation,  :patient_id => 1

       tid = apmt.id

     when "deleted"
       Appointment.find(id).destroy
       tid = id

     when "updated"
       apmt = Appointment.find(id)
       apmt.start_date = start_date
       apmt.end_date = end_date
       apmt.text = observation
       apmt.patient_id = 1
       apmt.save
       tid = id
   end

   render :json => {
              :type => mode,
              :sid => id,
              :tid => tid,
          }
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/medical_histories_helper.rb
module MedicalHistoriesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_appointment.html.erb
<tr>
      <td class="hidden-xs">
        <%=  appointment.id %>
      </td>
      <td>
        <%=  appointment.start_date.strftime("%d/%m/%Y") %>
      </td>
      <td>
         <%= link_to truncate(appointment.patient.full_name),appointment %>
       </td>
       <td>
         <%=  appointment.start_date.strftime("%H:%M%p")%>
        </td>
        <td >
           <%=  appointment.end_date.strftime("%H:%M%p")%>
         </td>
         <td class="hidden-xs" >

        </td>
        <td class="hidden-xs">

       </td>
      <td class="hidden-xs">
        <%= link_to "" , edit_appointment_path(appointment), id:"edit_#{appointment.id}", class: 'btn btn-warning glyphicon glyphicon-pencil'%>
      </td>
      <td class="hidden-xs">
        <%= link_to "" , appointment_path(appointment),method: :delete, id:"edit_#{appointment.id}", class: 'btn btn-danger glyphicon glyphicon-remove ',data: { confirm: '¿Seguro que quiere eliminar este paciente?' }%>
      </td>
</tr>

app/views/appointments/_form.html.erb
<div class="row">
  <div class="col-lg-8">
    <%= form_for @appointment, class: "form-horizontal" do |f| %>
    <% if @appointment.errors.any?%>
      <% @appointment.errors.full_messages.each do |error|%>
        <%= error.inspect%>
    <% end %>
    <% end %>
    <div class="container-fluid ">
      <div class="form-group ">
        <h4>Datos de la cita</h4>
        <hr>
        <h5><%= f.label :"Paciente: ", class: "col-sm-8 control-label" %></h5>
        <%= f.collection_select(:patient_id, current_user.patients, :id, :full_name ,class: 'form-control') %>
      </div>
      <div class="form-group ">
        <h5><%= f.label :"Fecha y hora de inicio: ", class: "col-sm-6 control-label" %></h5>
        <%= f.datetime_select  :start_date %>


        <br>
      </div>
      <div class="form-group ">
        <h5><%= f.label :"Hora de fin: ", class: "col-sm-6 control-label" %></h5>
        <%= f.datetime_select  :end_date %>


        <br>
      </div>
      <div class="form-group ">
        <br>
        <h4 >Observaciones adicionales</h4>
        <hr>
        <br>
        <%= f.text_area  :observation ,class: "form-control"%>
      </div>

    <div class="form-group col-md-offset-11">
      <br>
      <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/appointments/edit.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div >
  <h3>Modificar Cita</h3>
  <hr>
  <br>
    <%= render 'form' %>

</div>

app/views/appointments/index.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div class="row">
  <div class="col-lg-8">
    <h1 class="tittle"> Todas las citas </h1>
    <table class="table">
    <thead class="thead-dark">


    <div class="col-md-4 col-md-offset-9 ">
      <%= form_tag patients_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Buscar", :name => nil %>
        </p>
      <% end %>
    </div>
      <tr>
        <th scope="col" class="hidden-xs">No.Cita</th>
        <th scope="col">Fecha</th>
        <th scope="col">Nombre completo</th>
        <th scope="col ">Hora Inicio</th>
        <th scope="col " >Hora Fin</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col" class="hidden-xs"></th>
        <th scope="col" class="hidden-xs"></th>
      </tr>
    </thead>
    <tbody id="appointments">
      <%= render @appointments %>
    </tbody>
  </table>
      <div class="col-md-offset-4">
        <%= paginate @appointments %>
    </div>
  </div>
</div>
</div>

app/views/appointments/new.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div >
  <h3>Cita Nueva</h3>
  <hr>
  <br>
    <%= render 'form' %>

</div>
 

app/views/appointments/show.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div class="row">
  <div class="col-lg-8">
    <div>
          <h2 align="center" class="tittle"> Cita de: <%= @appointment.patient.full_name %> </h2>
      </div>
    </div>
    <div class="col-lg-8">
        <br>
        <br>
        <h3>Datos de la cita</h3>
        <hr>
    </div>
    <div class="col-lg-3">
        <% apomt_today =@appointment.start_date%>
        <% apomt_end_today =@appointment.end_date%>
        <h4><strong>Fecha</strong></h4> <%= apomt_today.strftime("%d/%m/%Y") %> 
    </div>
    <div class="col-lg-3">
        <h4><strong>Hora inicio</strong></h4> <%= apomt_today.strftime("%H:%M %p")%>
    </div>
    <div class="col-lg-2">
        <h4><strong>Hora fin</strong></h4> <%= apomt_end_today.strftime("%H:%M %p")%>
    </div>


    <div class="col-lg-8">
      <br>
      <br>
      <h3>Observaciones adicionales</h3>
      <hr>
      <div class="col-md-offset-1 ">
        <br>
        </h4> <%= @appointment.observation  %>
      </div>
    </div>

  </div>
    <div class="col-md-offset-10 ">
      <br>
      <br>
      <%= link_to 'Eliminar', appointment_path(@appointment), method: :delete, class: 'btn btn-danger',data: { confirm: '¿Seguro que quiere eliminar esta cita?' } %>
      <%= link_to 'Editar', edit_appointment_path(@appointment), class: 'btn btn-primary' %>
      <br>
      <br>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dobbo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'dhtmlxscheduler', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'dhtmlxscheduler', 'data-turbolinks-track' => true %>

  </head>


  <body>
    <%= yield %>
    <%= js add_gritter(flash[:notice], title: "Notificacion de Dobbo", sticky: false) %>
  </body>


  <footer class="footer p-t-10">
        <div>
          <hr>
            <p class="h5 sidebar-color" align="center">
                DOBBO 2018
            </p>
        </div>
  </footer>

</html>

app/views/patients/_form.html.erb
<div class="row">
  <div class="col-lg-8">
    <%= form_for @patient, class: "form-horizontal" do |f| %>
    <% if @patient.errors.any?%>
      <% @patient.errors.full_messages.each do |error|%>
        <%= error.inspect%>
    <% end %>
    <% end %>
    <div class="container-fluid">
      <div class="form-group ">
        <h4>Datos Generales</h4>
        <hr>
        <h5><%= f.label :"nombre*", class: "col-sm-2 control-label" %></h5>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"apellido_paterno", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"apellido_materno*", class: "col-sm-4 control-label" %>
        <%= f.text_field  :maternal_surname, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"telefono*", class: "col-sm-4 control-label" %>
        <%= f.text_field  :telephone, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"correo_electronico*", class: "col-sm-4 control-label" %>
        <%= f.text_field  :email, class: "form-control" %>
      </div>
      <br>
      <hr>
      <br>
      <div class="form-group col-lg-6">
        <%= f.label :"fecha_de_nacimiento", class: "col-sm-6 control-label" %>
        <%= f.date_field  :date_birth, class: "form-control " %>

      </div>


      <div class="form-group col-lg-6">
        <%= f.label :edad, class: "col-sm-4 control-label" %>
        <%= f.number_field  :age, class: "form-control"%>
      </div>

      <div class="form-group col-lg-8">
        <br>
        <br>
        <%= f.label :"estado_civil", class: "col-sm-4 control-label" %>
        <%= f.select :civil_status, ['Soltero', 'Casado'], class: "form-control" %>
      </div>


      <div class="form-group col-lg-4">
        <br>
        <br>
        <%= f.label :"sexo", class: "col-sm-4 control-label" %>
        <%= f.select :gender, ['No especificado','Masculino', 'Femenino'], class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"escolaridad", class: "col-sm-4 control-label" %>
        <%= f.text_field  :scholarship, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"ocupación", class: "col-sm-4 control-label" %>
        <%= f.text_field  :occupation, class: "form-control" %>
      </div>

      <div class="form-group">
        <br>
        <br>
        <h4>Domicilio</h4>
        <hr>
        <%= f.label :"calle", class: "col-sm-4 control-label" %>
        <%= f.text_field  :street, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"numero", class: "col-sm-4 control-label" %>
        <%= f.number_field  :number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"colonia", class: "col-sm-4 control-label" %>
        <%= f.text_field  :suburb, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"ciudad", class: "col-sm-4 control-label" %>
        <%= f.text_field  :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"municipio", class: "col-sm-4 control-label" %>
        <%= f.text_field  :mun, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"estado", class: "col-sm-4 control-label" %>
        <%= f.text_field  :county, class: "form-control" %>
      </div>

      <div class="form-group">
        <br>
        <br>
        <h4>Motivo de la visita</h4>
        <hr>
        <%= f.text_area :reason_desc, class: "form-control" %>
      </div>



    </div>
    <div class="form-group form-group col-md-offset-11">
      <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/patients/_patient.html.erb
<tr>
      <td>
        <%= patient.id%>
      </td>
      <td>
         <%= link_to truncate(patient.full_name),patient %>
       </td>
       <td>
          <%= patient.telephone %>
        </td>
        <td class="hidden-xs">
           <%= patient.email %>
         </td>

      <td class="hidden-xs">
        <%= link_to "" , edit_patient_path(patient), id:"edit_#{patient.id}", class: 'btn btn-warning glyphicon glyphicon-pencil'%>
      </td>
      <td class="hidden-xs">
        <%= link_to "" , patient_path(patient),method: :delete, id:"edit_#{patient.id}", class: 'btn btn-danger glyphicon glyphicon-remove ',data: { confirm: '¿Seguro que quiere eliminar este paciente?' }%>
      </td>
      <td class="hidden-xs">
        <%= link_to "Consulta" , patient_path(patient),method: :delete, id:"edit_#{patient.id}", class: 'btn btn-info ', data: { confirm: '¿Seguro que quiere eliminar este paciente?' }%>
      </td>
</tr>

app/views/patients/edit.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div class="row">
  <h1>Editar paciente</h1>
  <hr>
  <br>
<%= render 'form' %>

app/views/patients/index.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div class="row">
<div class="col-lg-8">
    <h1 class="tittle"> Todos los pacientes </h1>
      <table class="table">
      <thead class="thead-dark">


      <div class="col-md-5 col-md-offset-8 ">
        <%= form_tag patients_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Buscar", :name => nil %>
          </p>
        <% end %>
      </div>
        <tr>
          <th scope="col">No. Paciente</th>
          <th scope="col">Nombre completo</th>
          <th scope="col ">Telefóno</th>
          <th scope="col" class="hidden-xs">Email</th>
          <th scope="col" class="hidden-xs"></th>
          <th scope="col" class="hidden-xs"></th>
          <th scope="col" class="hidden-xs">

          </th>
        </tr>
      </thead>
        <tbody id="patients">
          <%= render @patients %>
        </tbody>
    </table>
      <div class="col-md-offset-4">
        <%= paginate @patients %>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
<div >
  <h3>Paciente Nuevo</h3>
  <hr>
  <br>
  <p> * campos obligatorios </p>
<%= render 'form' %>
</div>

app/views/patients/show.html.erb
<%= render 'shared/nav' %>
<div class="container-fluid">
    <%= render 'shared/sidenavbar'%>
  <div class="row">

    <div class="col-lg-8">
      <div>
            <h2 align="center" class="tittle"><%= @patient.full_name %> </h2>
        </div>
        <div >
            <br>
            <br>
            <h3>Datos Generales</h3>
            <hr>
        </div>
          <div class="col-lg-4">
      		    <h4><strong>Número de paciente</strong></h4> <%= @patient.id %>
          </div>

          <% if @patient.age %>
          <div class="col-lg-4">
      		    <h4><strong>Edad</strong></h4> <%= @patient.age %>
          </div>
          <%end%>

          <% if @patient.date_birth %>
          <div class="col-lg-4">
      		    <h4><strong>Fecha de nacimiento</strong></h4> <%= @patient.date_birth %>
          </div>
          <%end%>

          <% if @patient.gender %>
          <div class="col-lg-4">
            <br>
      		    <h4><strong>Sexo</strong></h4> <%= @patient.gender %>
          </div>
          <%end%>

          <% if !@patient.scholarship.eql?("") %>
          <div class="col-lg-4">
            <br>
      		    <h4><strong>Escolaridad</strong></h4> <%= @patient.scholarship  %>
          </div>
          <% end %>

          <% if !@patient.occupation.eql?("") %>
          <div class="col-lg-4">
            <br>
      		    <h4><strong>Ocupación</strong></h4> <%= @patient.occupation  %>
          </div>
          <%end%>


          <div class="col-lg-4">
            <br>
              <h4><strong>Estado civil:</strong></h4> <%= @patient.civil_status  %>
          </div>


          <div class="col-lg-4">
            <br>
      		    <h4><strong>Telefono:</strong></h4> <%= @patient.telephone  %>
          </div>

          <div class="col-lg-4">
            <br>
              <h4><strong>Correo Electronico:</strong></h4> <%= @patient.email  %>
          </div>

          <div class="col-lg-11">
            <br>
            <br>
              <h3>Domicilio</h3>
              <hr>
          </div>

          <% if !@patient.street.eql?("") %>
          <div class="col-lg-4">
            <h4><strong>Calle</strong></h4> <%= @patient.street  %>
          </div>
          <%end%>

          <% if @patient.number %>
          <div class="col-lg-4">
            <h4><strong>Número</strong></h4> <%= @patient.number  %>
          </div>
          <%end%>

          <% if !@patient.suburb.eql?("") %>
          <div class="col-lg-4">
            <h4><strong>Colonia</strong></h4> <%= @patient.suburb  %>
          </div>
          <%end%>

          <% if !@patient.city.eql?("") %>
          <div class="col-lg-4">
            <br>
            <h4><strong>Ciudad</strong></h4> <%= @patient.city  %>
            <br>
          </div>
          <%end%>

          <% if !@patient.mun.eql?("") %>
          <div class="col-lg-4">
            <br>
            <h4><strong>Municipio</strong></h4> <%= @patient.mun  %>
            <br>
          </div>
          <%end%>
          <% if !@patient.county.eql?("") %>
          <div class="col-lg-4">
            <br>
            <h4><strong>Estado</strong></h4> <%= @patient.county  %>
            <br>
          </div>
          <%end%>

          <div class="col-lg-11">
            <br>
            <br>
            <h3>Motivo de visita</h3>
            <hr>
          <% if !@patient.reason_desc.eql?("") %>
            <div class="col-md-offset-1 ">
              <br>
            </h4> <%= @patient.reason_desc  %>
            </div>
          <%end%>
          </div>
          <div class="col-lg-11">
            <br>
            <br>
              <h3>Todas las citas del paciente</h3>
              <hr>
          </div>

          <% @patient.appointments.each do |apmt| %>
            <div class='homepage-block col-md-3'>
              <p>
                <span class='pending-details'>Fecha:</span> <%= apmt.start_date.strftime("%d/%m/%Y") %>
              </p>
              <p>
                <span class='pending-details'>Hora Incio:</span> <%= apmt.start_date.strftime("%H:%M %p") %>
              </p>
              <p>
                <span class='pending-details'>Hora Fin:</span> <%= apmt.end_date.strftime("%H:%M %p") %>
              </p>
              <div class='col-md-11 column'>
                <%= link_to 'Detalles',appointment_path(apmt), id:"edit_#{apmt.id}", class: 'btn btn-info btn-block'  %>
              </div>
            </div>
          <%end%>

    </div>




  </div>
    <div class="col-md-offset-10 ">
      <br>
      <br>
      <%= link_to 'Eliminar', patient_path(@patient), method: :delete, class: 'btn btn-danger',data: { confirm: '¿Seguro que quiere eliminar este paciente?' } %>
      <%= link_to 'Editar', edit_patient_path(@patient), class: 'btn btn-primary' %>
      <br>
      <br>
    </div>

</div>

app/views/shared/_nav.html.erb
<nav class="navbar mynav navbar-default " >
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand font-color " >DOBBO</a>
   </div>
   <ul class="nav navbar-nav">
     <li class="<%=active?(root_path)%>">
			 <%= link_to "", root_path, class: 'glyphicon glyphicon-home font-color', :style=> 'color:#FFFFFF;' %>
		 </li>
     <li class="<%=active?(diary_show_path)%>">
			 <%= link_to "", diary_show_path, class: ' font-color glyphicon glyphicon-book', :style=> 'color:#FFFFFF;' %>
		 </li>
   </ul>
   <ul class="nav navbar-nav navbar-right">
     <li><a class="font-color navbar-font">
       <%=current_user.full_name%>
     </a>
   </li>
		 <li class="<%=active?(edit_user_registration_path)%>">
			 <%= link_to "", edit_user_registration_path, class: 'glyphicon glyphicon-user font-color', :style=> 'color:#FFFFFF;' %>
		 </li>
     <li >
			 <%= link_to "", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out font-color', :style=> 'color:#FFFFFF;' %>
		</li>
 	</ul>
 </div>
</nav>

app/views/shared/_sidenavbar.html.erb
<div class="col-lg-3">
  <div id="sidebar" class="well sidebar-nav ">
    <h5><i class="glyphicon glyphicon-user"></i>
      <small ><b>PACIENTES</b></small>
    </h5>
    <ul class="nav nav-pills nav-stacked">
      <li class="<%=active?(patients_path)%>"><%= link_to "Todos los pacientes", patients_path,class:"sidebar-color"%></li>
      <li class="<%=active?(new_patient_path)%>"><%= link_to "Nuevo paciente", new_patient_path, class:"sidebar-color"%></li>
    </ul>
    <h5><i class="glyphicon  glyphicon glyphicon-calendar "></i>
      <small><b>CITAS</b></small>
    </h5>
    <ul class="nav nav-pills nav-stacked">
      <li class="<%=active?(appointments_path)%>"><%= link_to "Todas las citas", appointments_path,class:"sidebar-color"%></li>
      <li class="<%=active?(new_appointment_path)%>"><%= link_to "Nueva Cita",new_appointment_path, class:"sidebar-color"%></li>
    </ul>
  </div>
</div>